### ISSUE TITLE
wrong account

### ISSUE THREAD

**Issue by TheAwesome98-Real** [00p513-dev/uranium#3]
I did a commit with the wrong account, can you delete those commits?

**Comment by 00p513-dev** [comment]
cant delete, but you have reverted it anyway basically so were chill

**Comment by TheAwesome98-Real** [comment]
yeah but it's still in the commits thing

**Comment by 00p513-dev** [comment]
it cant be removed i dont think

**Comment by TheAwesome98-Real** [comment]
i'm not really that good with git, but can't you do ```git reset``` 3 times or something? cause there haven't been any commits after what i did that i can see
